In [8]:
house_size=[400,500,600,700,800,900,1000,1100,1200,1300]
room_size=[20,25,30,35,40,45,50,55,60,65]
house_price=[800,1000,1200,1400,1600,2000,2200,2400,2600]
array1=np.array([[house_size],[room_size],[house_price]])
print(array1)


[[list([400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300])]
 [list([20, 25, 30, 35, 40, 45, 50, 55, 60, 65])]
 [list([800, 1000, 1200, 1400, 1600, 2000, 2200, 2400, 2600])]]


In [10]:
new_array=array1.transpose()
print(new_array)

[[list([400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300])
  list([20, 25, 30, 35, 40, 45, 50, 55, 60, 65])
  list([800, 1000, 1200, 1400, 1600, 2000, 2200, 2400, 2600])]]


In [15]:
print("Shape of Array: ",array1.shape)

Shape of Array:  (3, 1)


In [16]:
import numpy as np
def fonk1(a,b):
    arr=np.ones((a,b))
    i=0
    while i<a:
        j=0
        while j<b:
            if (i%2==0 and j%2==0):
                arr[i][j]=0
            j=j+1
        i=i+1
    
            
    return arr
print(fonk1(6,5))

[[0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1.]
 [0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1.]
 [0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1.]]
